name: universal_html
version: 1.1.1
description: Cross-platform 'dart:html'. Works in browser, server-side, and Flutter.
homepage: https://github.com/terrier989/universal_html
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  async: ^2.3.0
  charcode: ^1.1.2
  collection: ^1.14.11
  csslib: ^0.16.0
  html: ^0.14.0
  meta: ^1.1.7
  typed_data: ^1.1.6
  universal_io: '>=0.7.3 <0.9.0'
  xml: ^3.5.0
  zone_local: ^0.1.1

dev_dependencies:
  pedantic: ^1.8.0
  stream_channel: ^2.0.0
  test: ^1.6.3