name: generate_reflection
version: 0.0.1

environment:
  # We use the latest SDK
  sdk: '>=2.5.0-dev.1.0 <3.0.0'

dependencies:
  analyzer: any
  build: ^1.0.0
  universal_html:
    path: "../.."

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0