name: generate_reflection
version: 0.0.1

environment:
  # We use the latest SDK
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  analyzer: ^0.41.1
  build: ^1.6.1
  universal_html:
    path: "../.."

dev_dependencies:
  build_runner: ^1.10.12
  build_web_compilers: ^2.16.0