name: web_browser
version: 0.2.1
description: Widgets for showing web pages and web content. Uses webview_flutter in Android/iOS and
  iframe in browsers.
homepage: https://github.com/dint-dev/web_browser

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  meta: ^1.1.0
  share: ^0.6.0
  universal_html: '^1.2.3'
  webview_flutter: '^0.3.22'

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

#dependency_overrides:
#  universal_html:
#    path: '../universal_html'

flutter:
