name: universal_html
version: 1.2.2
description:
  A 'dart:html' that works in all platforms, including Flutter and server-side.
  Eases cross-platform development and other HTML / XML processing.
homepage: https://github.com/dint-dev/universal_html

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  async: ^2.3.0
  charcode: ^1.1.0
  collection: ^1.14.0
  csslib: '>=0.14.1 <0.17.0'
  html: '>=0.13.4 <0.15.0'
  meta: ^1.1.0
  typed_data: ^1.1.0
  universal_io: '>=0.8.5 <2.0.0'
  zone_local: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.0
  stream_channel: ^2.0.0
  test: ^1.8.0