name: generate_reflection
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  build: ^1.6.3
  universal_html:
    path: '..'

dev_dependencies:
  build_runner: ^1.11.5
  build_web_compilers: ^2.16.4
  pedantic: ^1.11.0