name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
        working-directory: universal_html
      - name: Run tests
        run: pub run test --platform vm
        working-directory: universal_html